language: java
after_success:
- mvn deploy
before_install:
- openssl aes-256-cbc -K $encrypted_01e7538b60ac_key -iv $encrypted_01e7538b60ac_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
notifications:
  email:
  - arena-uqbar@googlegroups.com
